version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "db_aiohttp"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./app:/app
    env_file:
      - ./_env
    expose:
      - 8080
